// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYA66OryjTMma28LTtliFxqSYygs5gAZA',
    appId: '1:316749649272:web:8a5a51b11d44288486e48d',
    messagingSenderId: '316749649272',
    projectId: 'smart-city-3f2b2',
    authDomain: 'smart-city-3f2b2.firebaseapp.com',
    storageBucket: 'smart-city-3f2b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWlv_wHmweLv5mc0MU6Qfe6qlaEoQ0O7s',
    appId: '1:316749649272:android:f95d044ba0caa00786e48d',
    messagingSenderId: '316749649272',
    projectId: 'smart-city-3f2b2',
    storageBucket: 'smart-city-3f2b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZg-3Sski9NlZGIvh-mePsNEzaraV4PQE',
    appId: '1:316749649272:ios:a303c61e252952a386e48d',
    messagingSenderId: '316749649272',
    projectId: 'smart-city-3f2b2',
    storageBucket: 'smart-city-3f2b2.firebasestorage.app',
    iosBundleId: 'com.example.smartCityReporting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZg-3Sski9NlZGIvh-mePsNEzaraV4PQE',
    appId: '1:316749649272:ios:a303c61e252952a386e48d',
    messagingSenderId: '316749649272',
    projectId: 'smart-city-3f2b2',
    storageBucket: 'smart-city-3f2b2.firebasestorage.app',
    iosBundleId: 'com.example.smartCityReporting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYA66OryjTMma28LTtliFxqSYygs5gAZA',
    appId: '1:316749649272:web:24e84cb2f26ae48786e48d',
    messagingSenderId: '316749649272',
    projectId: 'smart-city-3f2b2',
    authDomain: 'smart-city-3f2b2.firebaseapp.com',
    storageBucket: 'smart-city-3f2b2.firebasestorage.app',
  );
}
